export const PROFILE_ROUTE = '/profile'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_PAGE_ROUTE = '/'
export const TOURNAMENTS_ROUTE = '/tournaments'
export const RATING_ROUTE = '/rating'
export const COMMANDS_ROUTE = '/commands'